sudo: required
language: java
language: kotlin
language: cpp
compiler:
  - gcc
os:
  - linux
jdk:
  - oraclejdk8
script:
  - "cmake -DCMAKE_BUILD_TYPE= -G \"CodeBlocks - MinGW Makefiles\" jni"
  - "./gradlew check"
  - "./gradlew build"
before_install:
  - chmod a+x gradlew