sudo: required
language: java
language: kotlin
language: cpp
compiler:
  - gcc
os:
  - linux
jdk:
  - oraclejdk8
script:
# cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - MinGW Makefiles" jni
  - "cmake jni"
  - "cmake --build . --target all -- -j 8"
  - "./gradlew check"
  - "./gradlew build"
before_install:
  - chmod a+x gradlew
addons:
  apt:
    sources:
      # cmake 3.2.3 / doxygen 1.8.3
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data